name: Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Build entire solution (API + Tests)
        run: dotnet build SimpleGreetingApi.sln --configuration Debug

      - name: Run unit tests
        run: dotnet test SimpleGreetingApi.sln --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: GreetingApi
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish
